### ISSUE TITLE
Add category filter for seminar, problems

### ISSUE THREAD

**Issue by KSAlpha** [PLUS-POSTECH/study.plus.or.kr#22]
문제 및 세미나 주제 (Pwn, Reversing, Forensics, etc.)로 필터링이 가능하게 하면 좋을 것 같습니다.

시나리오:
1. 유저가 문제 리스트 또는 세미나를 조회할 때, 특정 카테고리로 필터할 수 있는 UI를 발견할 수 있습니다.
  ![image](https://user-images.githubusercontent.com/20783308/42299000-bcc9c646-8043-11e8-8308-e53a805fb964.png)
 https://semantic-ui.com/modules/dropdown.html 참조
2. 유저는 해당 UI에서 현재 등록되어있는 모든 카테고리를 볼 수 있습니다.
3. 유저가 필터 UI에서 카테고리를 선택하면, 문제 리스트 및 세미나의 내용 중 해당 카테고리에 속하는 것만 표시됩니다.

**Comment by kinux98** [comment]
이쿠~

**Comment by KSAlpha** [comment]
Merged #38
