### ISSUE TITLE
Improve home page

### ISSUE THREAD

**Issue by KSAlpha** [PLUS-POSTECH/study.plus.or.kr#25]
홈 화면이 너무 아무 것도 없는 느낌.

세미나 현황 (오늘의 세미나), 공지 사항, 현재 활성화 된 세션 등을 활용해 홈 화면을 꾸미자.

- [x] auth log 추가 @imnotkind 
- [x] 공지사항(문제 공지사항과는 다른) @kinux98 
- [x] 유저 status 띄워주기 @physicube

**Comment by kinux98** [comment]
어차피 세션은 is_active 꺼져있으면 소속된 problem_list 하고 problem들은  problem 탭에서 안보여서, 따로 problem list가 active한 세션에 포함되어 있는 걸 알려줄 필요가 있을까요... 그냥 problem 탭에서 보이는 것이 active한 세션인 것이구요..

**Comment by KSAlpha** [comment]
만약에 실제 CTF처럼 시간 단위로 쪼개지면 모르겠지만, 문제 리스트들이 Session단위로 쪼개지기 때문에 남은 시간 표시한다는게 의미가 있는 일인지 잘 모르겠는데 설명해주시면 감사하겠습니다.

**Comment by kinux98** [comment]
현재 진행중인 여러 event(QE나 뉴비 선발 기간 등, 즉 session) 의 남은 시간등을 표시해 주는 것이 있으면 더 좋지 않을까.. 해서 제안해봤습니다. problem list별이 아닌, session 별로 시간을 나타내며, 시간이 다 되었을 시 문제 접근이 차단되는.. 뭐 ctf사이트 들과 비슷한 기능을 가지면 더 좋을것 같습니다.

**Comment by KSAlpha** [comment]
이 부분은 추가적인 모델 수정이 필요하겠네요... 아마 현재 이슈와는 주제가 달라서 쪼개서 작업을 진행해야 할 듯 싶은데 이번 개발 분기에서는 제외하도록 하겠습니다.

**Comment by KSAlpha** [comment]
Merged #42
