### ISSUE TITLE
Add linters / CI

### ISSUE THREAD

**Issue by Qwaz** [PLUS-POSTECH/study.plus.or.kr#31]
Python is very dynamic language which makes it easy to write wrong code. Linters and analyzers can help preventing this problem.

Candidates:
* [Bandit](https://github.com/PyCQA/bandit) - A security linter from PyCQA
* [Flake8](http://flake8.pycqa.org/en/latest/) - Your Tool For Style Guide Enforcement
* [PyLint](https://www.pylint.org/) - code analysis for Python

**Comment by KSAlpha** [comment]
세개 CI 설정 해보겠습니다. 좋은 아이디어네요

**Comment by KSAlpha** [comment]
#34 merged
