### ISSUE TITLE
add favicon!!

### ISSUE THREAD

**Issue by imnotkind** [PLUS-POSTECH/study.plus.or.kr#33]
# Make plus study great again Project
### 후보 1
![image](https://user-images.githubusercontent.com/22850304/42521249-4faedbfa-84a3-11e8-8c59-ea26d5a08387.png)
### 후보 2
![image](https://user-images.githubusercontent.com/22850304/42521558-227632e0-84a4-11e8-82f2-7235d0f8319d.png)
### 후보 3
![image](https://user-images.githubusercontent.com/22850304/42521629-4c3c6bc6-84a4-11e8-91b3-16976b39f18b.png)
### 후보 4
![image](https://user-images.githubusercontent.com/22850304/42521698-6fa13074-84a4-11e8-89cf-b3fb5baa170d.png)
### 후보 5
![image](https://user-images.githubusercontent.com/22850304/42521801-a6ce8376-84a4-11e8-985f-cd0c60c77acd.png)

**Comment by KSAlpha** [comment]
이상한거 말고 할거면 1번으로 합시다;;;

**Comment by imnotkind** [comment]
저는 개인적으로 2번입니다

**Comment by KSAlpha** [comment]
2번은 아니야 ㅠㅠ

**Comment by imnotkind** [comment]
이미지 넣으려고 하는데 넣을만한 디렉토리를 프로젝트에 만드는 건 어떤가요? media/ 라든가... 
온라인 이미지로 넣어도 되는데 plus.or.kr에 있는 부엉이는 하얀 배경이 거슬리네요

**Comment by KSAlpha** [comment]
favicon 정도는 static 서브하면 될 것 같은데... 확인해보시죠

**Comment by Qwaz** [comment]
Django가 원래 프로덕션에서 스태틱 파일 서브는 안 하는걸 권장해요 nginx 등 웹서버 단에서 하라고 시키는데 저희는 귀찮으니까 그냥 Django에서 합시다

**Comment by physicube** [comment]
favicon 순서가 바뀌었는데요? ㅋㅋ

**Comment by KSAlpha** [comment]
Merged #41
