### ISSUE TITLE
model delete setting

### ISSUE THREAD

**Issue by imnotkind** [PLUS-POSTECH/study.plus.or.kr#54]
지금은 전부 model.protect로 돼있어서 불편하다

**Comment by imnotkind** [comment]
CASCASDE와 
SET NULL 정도를 필요에 따라 추가하면 될 듯

**Comment by KSAlpha** [comment]
일단 PROTECT 푸는건 비추

CASCADE는 매우 공격적이고 SET_NULL은 코드 상에서 오류를 낼 가능성이 큼. 삭제를 해주는 인터페이스를 따로 만들어서 CASCADE에 대한 위험성을 인지시키거나, 완전히 안전한 방법으로 deleted 필드를 추가해서 다루는게 좋음.

레코드를 지워야하는 특별한 이유가 있는지?

**Comment by imnotkind** [comment]
이게 생각난 이유는 신입생 중에 나간다는 아이가 있어서 그랬습니다만
그거 말고도 현재 신입생 문제 개편 중에 인스턴스를 지우고 싶을때 auth log때문에 인스턴스가 지워지지 않습니다.

**Comment by imnotkind** [comment]
대응책으로 can delete 권한을 제한시키는건 어떤가요? 너무 위험해서 대응책이 필요할것같다고는 생각했습니다
![image](https://user-images.githubusercontent.com/22850304/55155473-ca28dd80-519a-11e9-8812-d8cbac860bfb.png)

**Comment by KSAlpha** [comment]
user-Auth log관계는 퍼블 때문에 되도록이면 보존하는게 좋고, 신입생이 나간다고해서 계정을 지울필요는 없고 disable만 시키면 될것 같습니다.

인스턴스 지우는거 자체도 사실 지양해야할 부분이긴한데, 인스턴스 - authlog 간에는 cascade 시켜도 될것 같네요.

**Comment by imnotkind** [comment]
알겠습니다. 일단 ProblemInstance-AuthLog 부분만 CASCADE를 적용하는 걸로 마무리하겠습니다. (수동으로 지우는게 너무 힘들 수준이므로)
USER도 is_active가 django에서 기본으로 제공하고 권장하는 방식이군요. 감사합니다.

**Comment by KSAlpha** [comment]
#58 에서 model 변경됐는데, migration 안하면 실적용안될 수 있습니다. 확인해주세요.

**Comment by imnotkind** [comment]
migration을 까먹었는데도 제대로 적용은 되더군요.
허나 migration을 해도 migration 파일이 따로 생성이 안 되는 것 같은데, 혹시 정상인가요?
![image](https://user-images.githubusercontent.com/22850304/55289719-39a20580-5405-11e9-9600-ae7259dc5c4c.png)
![image](https://user-images.githubusercontent.com/22850304/55289726-51798980-5405-11e9-89ed-ffa208c7becd.png)

**Comment by KSAlpha** [comment]
작업을 온라인 서버에서 직접 하는건 좋지 않습니다.

로컬 개발 환경에서도 동일한가요?

**Comment by imnotkind** [comment]
ㅋㅋㅋ 너무 귀찮아서 그만... 이따가 로컬로 확인해보겠습니다.

**Comment by imnotkind** [comment]
로컬 개발환경에서 확인한 결과 파일이 제대로 생성됩니다.

**Comment by imnotkind** [comment]
서버에서 migration 파일이 잘 적용된 것을 확인했습니다.
![image](https://user-images.githubusercontent.com/22850304/55294102-d3cf7100-5438-11e9-917f-8e377ffa7d05.png)

**Comment by imnotkind** [comment]
아 당연하죠. docker-compose production 설정으로는 소스 파일이 host와 공유 안 되기 때문입니다. :)

**Comment by KSAlpha** [comment]
오... 그랬었군요
