### ISSUE TITLE
New feature : Shop

### ISSUE THREAD

**Issue by imnotkind** [PLUS-POSTECH/study.plus.or.kr#62]
shop을 만들자.
- problem list당 score로 만드는 shop

**Comment by imnotkind** [comment]
shop과 problem list는 OneToOneField.
shop의 title과 description은 없애버림. (rank처럼 problem_list로 대변됨)

**Comment by imnotkind** [comment]
ShopPurchaseLog 는 오직 운이 나빠서 탈락했을때만 succeed=False, 성공했을때는 succeed=True.
그 외에 돈이 부족하거나 stock이 없을 경우에는 로그를 아예 남기지 말자.

**Comment by imnotkind** [comment]
item과 shop이 ManyToMany라서 stock을 적용하기 애매해서 일단 stock은 추후에 적용하는걸로.

**Comment by imnotkind** [comment]
image는 static에다 올리는게 나을듯

**Comment by imnotkind** [comment]
구매를 한 뒤에 modal로 결과를 알려주는데 modal hide가 시작하면 리로딩을 할 때, 사람들이 연타를 하느라 막 눌러서 원치 않는 구매가 일어나는 현상이 확인됨.

**Comment by KSAlpha** [comment]
버튼 한번 누르면 비활성화?

**Comment by imnotkind** [comment]
캬 좋네요. hotfix하겠습니다.

**Comment by imnotkind** [comment]
내가 15%를 해놨는데 생각외로 개털려서 재빨리 stock을 만들어야겠습니다.

**Comment by imnotkind** [comment]
또 버튼을 누르면 비활성화를 하고 
버튼 로딩에도 시간이 꽤 걸리므로 버튼 로딩때까지 비활성화를 해두겠습니다.

**Comment by imnotkind** [comment]
stock이 db에 고정되어 있고 log로 남아있는 stock을 계산하는 방법이 있고,  
또 하나를 살때마다 db에 있는 stock값을 -1 하는 방법이 있지만,
후자가 좀 더 구현이 쉬우므로(위험해 보이긴 하지만) 일단은 후자로 하겠습니다.

**Comment by imnotkind** [comment]
추후 상점 아이템에 author를 추가하고, Inventory에서 자신의 당첨된 상품이 보이도록, 또 거기에서 수령확인을 할 수 있도록 만들자.

**Comment by imnotkind** [comment]
또 어디 Recent solve처럼 성공한 사람들의 로그 표시하자!

**Comment by imnotkind** [comment]
description에 linebreak
