### ISSUE TITLE
db backup

### ISSUE THREAD

**Issue by imnotkind** [PLUS-POSTECH/study.plus.or.kr#71]
container의 `/var/lib/postgresql/data`랑
host의 디렉토리랑 volume 연결

**Comment by beta-lux** [comment]
Host 디렉토리에 연결할 경우에 해당 디렉토리가 root 권한으로 잡혀서 운용이 불편해집니다. 일반 도커 볼륨으로 연결하는건 어떨까요?

**Comment by imnotkind** [comment]
좋습니다 저도 제 홈폴더에 root권한 쓰레기때매 sudo의 힘을 빌렸었습니다

**Comment by imnotkind** [comment]
우리들의 염원이 이루어져따
https://github.com/PLUS-POSTECH/study.plus.or.kr/commit/e8ebff406eafa4e47fceea413460d20b064665d3
