### ISSUE TITLE
Hidden problems are not hidden.

### ISSUE THREAD

**Issue by beta-lux** [PLUS-POSTECH/study.plus.or.kr#83]
문제 인스턴스를 히든으로 설정해도 /get/[instance-id] 에 요청할 경우에 문제 내용을 볼 수 있습니다.
[instance-id]가 단순한 Number PK이기 때문에, 사용자가 충분히 히든 문제를 열람할 수 있습니다.

**Comment by beta-lux** [comment]
Fixed by PR #85

**Comment by imnotkind** [comment]
분기의 isActive 체크도 필요 ㅂㄷㅂㄷ

**Comment by imnotkind** [comment]
그리고 떠오른 건데 저 친구가 인증을 했으니 인증도 체크로직이 없겠군요 후...

**Comment by imnotkind** [comment]
![image](https://user-images.githubusercontent.com/22850304/111905031-07c05880-8a8d-11eb-81d8-1bcee54fcbf3.png)
![image](https://user-images.githubusercontent.com/22850304/111905138-97fe9d80-8a8d-11eb-8739-464e891e68c5.png)


탐색창에서 검색되는 것하고
/problem?q= 인자로 GET할 때도

isActive와 is_staff 체크 필요

탐색창은 아마 client-side에서 솎아내는 거라 server-side에서부터 솎아내야할듯?
